evetool/crafts/urls.py
"""Path file"""

from django.urls import path
from crafts import views

urlpatterns = [
    path('', views.home, name="home"),
    path('info/', views.info, name="info"),
]

evetool/evetool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('crafts.urls')),
    path('admin/', admin.site.urls),
]

evetool/crafts/models.py
from django.db import models


class Category(models.Model):
    """categories model"""
    name = models.CharField(max_length=200, unique=True)
    categories_id = models.IntegerField(unique=True)


class Group(models.Model):
    """groups in a category"""
    name = models.CharField(max_length=200, unique=True)
    groups_id = models.IntegerField(unique=True)
    category_belong = models.ForeignKey(Category, on_delete=models.CASCADE)


class Item(models.Model):
    """items in a group"""
    name = models.CharField(max_length=200, unique=True)
    types_id = models.IntegerField(unique=True)
    group_belong = models.ForeignKey(Group, on_delete=models.CASCADE)
    week0_value = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    week1_value = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    month0_value = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    month1_value = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    week0_quantity = models.BigIntegerField(null=True)
    week1_quantity = models.BigIntegerField(null=True)
    month0_quantity = models.BigIntegerField(null=True)
    month1_quantity = models.BigIntegerField(null=True)


class Blueprint(models.Model):
    """blueprint model"""
    name = models.CharField(max_length=200, unique=True)
    types_id = models.IntegerField(unique=True)
    group_belong = models.ForeignKey(Group, on_delete=models.CASCADE)
    items_needed = models.ManyToManyField(Item, related_name="compo", through="InputProduction")
    items_produced = models.ForeignKey(Item, related_name="result", on_delete=models.CASCADE, null=True)
    quantity_produced = models.IntegerField(null=True)
    invention_data = models.ManyToManyField("self", through="Invention", symmetrical=False)
    tech_2 = models.BooleanField(default=False)
    reaction = models.BooleanField(default=False)
    time_prod = models.IntegerField(default=3600)


class Invention(models.Model):
    """data linked to invention"""
    input_blueprint = models.ForeignKey(Blueprint, related_name="input_bp", on_delete=models.CASCADE)
    output_blueprint = models.ForeignKey(Blueprint, related_name="output_bp", on_delete=models.CASCADE)
    items_needed = models.ManyToManyField(Item, through="InputInvention")
    time = models.IntegerField()
    run_per_success = models.IntegerField(default=1)
    succes_rate = models.DecimalField(max_digits=6, decimal_places=2)


class InputProduction(models.Model):
    """items needed for blueprint"""
    items = models.ForeignKey(Item, on_delete=models.CASCADE)
    blueprints = models.ForeignKey(Blueprint, on_delete=models.CASCADE)
    quantity = models.IntegerField()


class InputInvention(models.Model):
    """items needed for invention"""
    items = models.ForeignKey(Item, on_delete=models.CASCADE)
    inventions = models.ForeignKey(Invention, on_delete=models.CASCADE)
    quantity = models.IntegerField()

evetool/crafts/forms.py
from django import forms
from config import REACTIONS, COMPOSANTS, ITEMS, REACTION_STRUCTURES, RIGGS_PROD, \
    RIGGS_REACTION, MANUFACTURING_STRUCTURES, ARBORESCENCE, DECRYPTOR, SKILL, ME_LIST, TE_LIST


class CraftForm(forms.Form):
    reaction = forms.MultipleChoiceField(choices=REACTIONS,
                                         widget=forms.CheckboxSelectMultiple(attrs={'class': "form-check-input"}),
                                         required=False)
    composant = forms.MultipleChoiceField(choices=COMPOSANTS,
                                          widget=forms.CheckboxSelectMultiple(attrs={'class': "form-check-input"}),
                                          required=False)
    items = forms.MultipleChoiceField(choices=ITEMS,
                                      widget=forms.CheckboxSelectMultiple(attrs={'class': "form-check-input"}),
                                      required=False)
    reaction_structures = forms.ChoiceField(choices=REACTION_STRUCTURES)
    reaction_rigg = forms.ChoiceField(choices=RIGGS_REACTION)
    item_t1_structures = forms.ChoiceField(choices=MANUFACTURING_STRUCTURES)
    item_t1_rigg = forms.ChoiceField(choices=RIGGS_PROD)
    item_t2_structures = forms.ChoiceField(choices=MANUFACTURING_STRUCTURES)
    item_t2_rigg = forms.ChoiceField(choices=RIGGS_PROD)
    fuel_block = forms.BooleanField(required=False)
    arborescence = forms.ChoiceField(choices=ARBORESCENCE)
    ME = forms.ChoiceField(choices=ME_LIST)
    TE = forms.ChoiceField(choices=TE_LIST)
    science1 = forms.ChoiceField(choices=SKILL)
    science2 = forms.ChoiceField(choices=SKILL)
    encryption = forms.ChoiceField(choices=SKILL)
    decryptor = forms.ChoiceField(choices=DECRYPTOR)

evetool/crafts/views.py
from django.shortcuts import render
from crafts.forms import CraftForm
from crafts.services import Services
from django.http import QueryDict


def home(request):
    """Tool home page."""
    if request.method == 'GET':
        form = CraftForm()
        return render(request, "crafts/research.html", {"form": form})
    elif request.method == "POST":
        f = CraftForm(request.POST)
        if f.is_valid():
            service = Services()
            data = service.make_list(f)
        return render(request, "crafts/research.html", {"form": f, "data": data})


def info(request):
    """Production detail page"""

    if request.method == 'POST':
        form = QueryDict(query_string=request.POST["form"], mutable=True)
        f = CraftForm(form)
        if f.is_valid():
            data = {
                "form": f,
                "item": request.POST["item"]
            }
            service = Services()
            data = service.show_info(data)
            return render(request, "crafts/info.html", {
                "form": f,
                "data": data
            })
    else:
        form = CraftForm()
        return render(request, "crafts/research.html", {"form": form})

evetool/crafts/templates/crafts/base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Datatable CSS -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">
    <title>EVE CRAFT</title>
</head>
<body>
    
    <div class="container bg-warning bg-gradient">
        <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
            EVE CRAFT - AUTOMATISATION DE CALCUL BENEF / PERTE
        </header>
    </div>

    <div class="container mt-5 bg-light p-3">
        <form action="/" method="POST">
            {% csrf_token %}
            <div class="row mb-3">
                <div class="col ml-5">
                    {% for checkbox in form.reaction %}
                    <div class="form-check">
                        {{ checkbox.tag }}
                        <label for="{{ checkbox.id_for_label }}" class="form-check-label">
                            {{ checkbox.choice_label }}
                        </label>
                    </div>
                    {% endfor %}
                </div>
                <div class="col ml-5">
                    {% for checkbox in form.composant %}
                    <div class="form-check">
                        {{ checkbox.tag }}
                        <label for="{{ checkbox.id_for_label }}" class="form-check-label">
                            {{ checkbox.choice_label }}
                        </label>
                    </div>
                    {% endfor %}
                </div>
                <div class="col ml-5">
                    {% for checkbox in form.items %}
                    <div class="form-check">
                        {{ checkbox.tag }}
                        <label for="{{ checkbox.id_for_label }}" class="form-check-label">
                            {{ checkbox.choice_label }}
                        </label>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="row mb-3">
                <div class="col">
                    <div class="form-check">
                        <label>Prod Fuel Block</label>
                        {{ form.fuel_block }}
                    </div>
                </div>
                <div class="col">
                    <div class="form-check">
                        <label>Arborescence</label>
                        {{ form.arborescence }}
                    </div>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col">
                    <div class="form-check">
                        <label for="id_reaction_structures">Reaction Structure</label>
                        {{ form.reaction_structures }}
                    </div>
                    <div class="form-check">
                        <label>Reaction Rigg</label>
                        {{ form.reaction_rigg }}
                    </div>
                </div>
                <div class="col">
                    <div class="form-check">
                        <label>Item_T1 Structure</label>
                        {{ form.item_t1_structures }}
                    </div>
                    <div class="form-check">
                        <label>Item_T1 Rigg</label>
                        {{ form.item_t1_rigg }}
                    </div>
                </div>
                <div class="col">
                    <div class="form-check">
                        <label>Item_T2 Structure</label>
                        {{ form.item_t2_structures }}
                    </div>
                    <div class="form-check">
                        <label>Item_T2 Rigg</label>
                        {{ form.item_t2_rigg }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    !! BP PIRATES METTRE ME 0 !!
                    <div class="form-check pt-2">
                        <label>BP ME</label>
                        {{ form.ME }}
                    </div>
                    <div class="form-check">
                        <label>BP TE</label>
                        {{ form.TE }}
                    </div>
                </div>
                <div class="col">
                    <div class="form-check">
                        <label>Science 1</label>
                        {{ form.science1 }}
                    </div>
                    <div class="form-check">
                        <label>Science 2</label>
                        {{ form.science2 }}
                    </div>
                    <div class="form-check">
                        <label>Encryption</label>
                        {{ form.encryption }}
                    </div>
                </div>
                <div class="col">
                    <div class="form-check">
                        <label>Decryptor</label>
                        {{ form.decryptor }}
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
     
    {% block Content%}{% endblock %}

     <!-- Bootstrap core JS-->
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
    <!-- Datatable js -->
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>

    <script src="{% static 'crafts/scripts.js' %}"></script>

</body>
</html>

evetool/crafts/templates/crafts/info.html
{% extends "./base.html" %}
{% load static %}

{% block Content %}
    <div class="container-fluid my-5">
        <h2 class="text-center text-success mb-3">{{ data.item_selected }}</h2>
        <div class="row justify-content-around">
            <div class="col-5 bg-warning text-center">
                LISTE DES COMPOSANTS
            </div>
            <div class="col-5 bg-warning text-center">
                COUT DES COMPOSANTS
            </div>
        </div>
        <div class="row justify-content-around">
            <div class="col-5 border">    
                {% for key, value in data.list_components.items %}
                   <div>{{ key }} ===> {{ value|floatformat }} unités</div>
                {% endfor %}
            </div>
            <div class="col-5">
                <div class="row border">
                    <div class="col">
                        Valeur des composants cette semaine: <b>{{ data.compo_value_week|floatformat }}</b><br>
                        Valeur des composants ce mois: {{ data.compo_value_month|floatformat }}
                    </div>
                    <div class="col">
                        Evolution prix cette semaine: <b>{{ data.compo_progress_week|floatformat }}%</b><br>
                        Evolution prix ce mois: {{ data.compo_progress_month|floatformat }}%
                    </div>
                </div>
                <div class="row mt-2 bg-warning">
                    <div class="col text-center">
                        VALEUR PRODUIT
                    </div>
                </div>
                <div class="row border">
                    <div class="col">
                        Valeur produit fini cette semaine: <b>{{ data.product_value_week|floatformat }}</b><br>
                        Valeur produit fini ce mois: {{ data.product_value_month|floatformat }}<br>
                        Volume quotidient cette semaine: {{ data.product_volume_week|floatformat }}<br>
                        Volume quotidient ce mois: {{ data.product_volume_month|floatformat }}
                    </div>
                    <div class="col">
                        Evolution prix cette semaine: <b>{{ data.product_progress_week|floatformat }}%</b><br>
                        Evolution prix ce mois: {{ data.product_progress_month|floatformat }}%<br>
                        Evolution volume cette semaine: {{ data.volume_progress_week|floatformat }}%<br>
                        Evolution volume ce mois: {{ data.volume_progress_month|floatformat }}%
                    </div>
                </div>
                <div class="row mt-2 bg-warning">
                    <div class="col text-center">
                        BENEF / PERTE
                    </div>
                </div>
                <div class="row border">
                    <div class="col">
                        Bénéfice par jour cette semaine: <b>{{ data.DAY_PROFIT_WEEK|floatformat }}</b><br>
                        Bénéfice par jour ce mois: {{ data.DAY_PROFIT_MONTH|floatformat }}<br>
                        Cycle par jour: {{ data.RUNS_DAY }}
                    </div>
                    <div class="col">
                        Evolution bénéfice cette semaine: <b>{{ data.DAY_PROFIT_WEEK_PROGRESS|floatformat }}%</b><br>
                        Evolution bénéfice ce mois: {{ data.DAY_PROFIT_MONTH_PROGRESS|floatformat }}%
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

evetool/crafts/templates/crafts/research.html
{% extends "./base.html" %}
{% load static %}

{% block Content%}
    {% if data %}
    <table class="table" id="table_id">
        <thead>
            <tr>
                <th scope="col">Nom</th>
                <th scope="col">Benefices / Jour</th>
                <th scope="col">Evolution</th>
                <th scope="col">Benefices / Jour (Mensuel)</th>
                <th scope="col">Evolution (Mensuel)</th>
                <th scope="col">Volumes / Jour</th>
                <th scope="col">Unités / Jour</th>
                <th scope="col">Détail</th>
            </tr>
        </thead>
        <tbody>
        {% for key, value in data.items %}
        <tr>
            <th scope="row">{{ key }}</th>
            <td>{{ value.DAY_PROFIT_WEEK|floatformat:"g" }}</td>
            <td>{{ value.day_profit_week_progress|floatformat }}</td>
            <td>{{ value.DAY_PROFIT_MONTH|floatformat }}</td>
            <td>{{ value.day_profit_month_progress|floatformat }}</td>
            <td>{{ value.volume }}</td>
            <td>{{ value.runs_day|floatformat }}</td>
            <td><button id="{{ key }}" type="submit" class="showinfo btn btn-primary">Show Info</button></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endif %}
{% endblock %}

evetool/crafts/templates/crafts/show_info.html
<!DOCTYPE html>
<html>
<head>
    <title>2e</title>
</head>
<body>
<div>
    {{ data }}
</div>
</body>
</html>